### ISSUE TITLE
[Feature] Neovim plugin for incorporating scooter

### ISSUE THREAD

**Issue by wakatara** [thomasschafer/scooter#10]
Realize it's a bit of a sidebar request, but searching and replacing across files in a project in neovim is still a bit meh (I use ripgrep and some internal vim commands, but it's error prone and finicky.). 

Would love to see this incporated into a neovim plugin.

**Comment by thomasschafer** [comment]
This is a nice idea - I'd be very happy for someone to implement this as a Neovim plugin! For now a good alternative would probably be to use [toggleterm](https://github.com/akinsho/toggleterm.nvim) to open up scooter in a floating terminal window. I'll close this issue for now as it won't be something that gets built in to scooter directly, but I'm happy to continue the conversation

**Comment by thomasschafer** [comment]
I've added a Neovim section [here](https://github.com/thomasschafer/scooter) with instructions on using Scooter with Toggleterm

**Comment by wakatara** [comment]
@thomasschafer Awesome! Will try it out tonight or tomorrow morning! Thank you!!
