### ISSUE TITLE
Not clear what "Fixed strings" means

### ISSUE THREAD

**Issue by cool-RR** [thomasschafer/scooter#23]
Does it mean not regex? If so it should probably say so explicitly. Some kind of documentation would be helpful.

**Comment by cool-RR** [comment]
I see now that "fixed strings" indeed means not regex. Should be made clearer in the UI in my opinion. You should probably avoid double negative, e.g. have two radio buttons "Fixed strings" and "Regex". If there's demand, you could have a third radio button "Wildcard". I personally don't use it but I think other people do.

**Comment by thomasschafer** [comment]
I've clarified the meaning of fixed strings in the readme, separately I'll look at updating the UI to make this a radio button if/when I add other options
