### ISSUE TITLE
Not clear how to operate on dotfiles

### ISSUE THREAD

**Issue by cool-RR** [thomasschafer/scooter#36]
It appears that Scooter by default ignores dotfiles. I wanted to do a replace on dotfiles. It wasn't clear how to override this setting. I tried `.*` in the filename regex, but that didn't fix it.

**Comment by thomasschafer** [comment]
Currently there's no option to include files or folders beginning with `.`, but this is something I'd like to add

**Comment by cool-RR** [comment]
Thank you!
