### ISSUE TITLE
A homebrew install option for Mac users

### ISSUE THREAD

**Issue by vassudanagunta** [thomasschafer/scooter#6]
If such were to exist, its usage will take off on macs. I'd almost say it's a requirement for that to occur.

It's the best balance between asking people to install Cargo and building from source (which will still happen under Homebrew) and providing an exe for every platform X hardware combo ([as this guy annoyingly demanded](https://news.ycombinator.com/item?id=42149198)).

**Comment by thomasschafer** [comment]
I'm going to add this very soon!

**Comment by wakatara** [comment]
I used to use goreleaser in one of my last rust projects (I use mostly Go these days) to handle this as well as adding in a tap for homebrew (and snaps). Easy way to have this work via a github workflow as well for releases. 

You can see the setup here: 
https://github.com/wakatara/harsh/blob/master/.goreleaser.yml

and here for the github action: 
https://github.com/wakatara/harsh/blob/master/.github/workflows/release.yml

**Comment by thomasschafer** [comment]
Added: https://github.com/thomasschafer/scooter/pull/49
