### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by cool-RR** [thomasschafer/scooter#7]
Any way I can get binaries of this for both Ubuntu and Windows, if it works on Windows?

**Comment by vassudanagunta** [comment]
A better solution would be a package manager solution for each platform (e.g. #6), though I don't know if one exists for Windows.

**Comment by thomasschafer** [comment]
Yes - I'm going to add binaries for various platforms soon!

**Comment by thomasschafer** [comment]
Also to add, contributions are very welcome here if anyone fancies adding binaries to their package manager of choice

**Comment by vassudanagunta** [comment]
I think the best thing about Homebrew is that you don't have to create binaries. I don't know if the package managers for other platforms work similarly. 

From [Wikipedia](https://en.m.wikipedia.org/wiki/Homebrew_(package_manager)):

> The package manager builds software from source using "formulae", Ruby scripts constructed with the Homebrew domain-specific language (DSL) for managing dependencies, downloading source files, and configuring and compiling software. Binary packages called "bottles" provide pre-built formulae with default options.

**Comment by thomasschafer** [comment]
Pre-built binaries are now available from the [releases page](https://github.com/thomasschafer/scooter/releases/tag/v0.1.2) (documented [here](https://github.com/thomasschafer/scooter/?tab=readme-ov-file#prebuilt-binaries)). I'll close this for now but I'm still looking to add scooter to a number of packages managers, including Homebrew
