### ISSUE TITLE
Nix package PR is open

### ISSUE THREAD

**Issue by felixzieger** [thomasschafer/scooter#9]
Hey, I wanted to let you know that I opened https://github.com/NixOS/nixpkgs/pull/356310 to make scooter available as a package for nix.

@thomasschafer If you add installation instructions for other package managers, you could mention nix there once the PR is merged. Maybe similar to how it's done for [dua-cli](https://github.com/byron/dua-cli?tab=readme-ov-file#nixos):

### Installation

...

#### NixOS

Nix-shell (temporary)

```
nix-shell -p scooter
```

NixOS configuration

```
  environment.systemPackages = [
    pkgs.scooter
  ];
```

**Comment by thomasschafer** [comment]
Thank you so much @felixzieger! Let me know when it's merged and I'll update the readme here (or feel free to open a PR if you fancy it 😃)
